# Generated by Django 3.2.7 on 2021-09-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fields', models.CharField(choices=[('datetime', (('true', 'required'), ('true', 'not required'))), ('integer', (('true', 'required'), ('true', 'not required'))), ('text', (('true', 'required'), ('true', 'not required'))), ('textarea', (('true', 'required'), ('true', 'not required')))], max_length=5)),
            ],
        ),
    ]
