# Generated by Django 3.2.7 on 2021-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='fields',
        ),
        migrations.AddField(
            model_name='column',
            name='date_time_field',
            field=models.CharField(choices=[('datetime', (('true', 'required'), ('false', 'not required')))], default='null', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='integer_field',
            field=models.CharField(choices=[('integer', (('true', 'required'), ('false', 'not required')))], default='null', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='text_field',
            field=models.CharField(choices=[('text', (('true', 'required'), ('false', 'not required')))], default='null', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='textarea_field',
            field=models.CharField(choices=[('textarea', (('true', 'required'), ('false', 'not required')))], default='null', max_length=5),
            preserve_default=False,
        ),
    ]
