# Generated by Django 3.2.7 on 2021-09-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_auto_20210920_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='date_time_field',
            field=models.CharField(choices=[('datetime', (('true', 'required'), ('false', 'not required')))], max_length=5),
        ),
        migrations.AlterField(
            model_name='column',
            name='integer_field',
            field=models.CharField(choices=[('integer', (('true', 'required'), ('false', 'not required')))], max_length=5),
        ),
        migrations.AlterField(
            model_name='column',
            name='textarea_field',
            field=models.CharField(choices=[('textarea', (('true', 'required'), ('false', 'not required')))], max_length=5),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('integer', models.IntegerField(null=True)),
                ('text_area', models.TextField(null=True)),
                ('chars', models.CharField(max_length=52, null=True)),
                ('column_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columns.column')),
            ],
        ),
    ]
